### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by pmcelhaney** [lykmapipo/nodejs-cucumber-sample#3]
I'm having the hardest time getting a simple demo of Cucumber to work. Here's what I get with this repo. 

Any help you can provide is much appreciated. 

``` sh
~/code
$ git clone https://github.com/lykmapipo/nodejs-cucumber-sample.git
Cloning into 'nodejs-cucumber-sample'...
remote: Counting objects: 22, done.
remote: Total 22 (delta 0), reused 0 (delta 0), pack-reused 22
Unpacking objects: 100% (22/22), done.
Checking connectivity... done.

~/code
$ cd nodejs-cucumber-sample/
/Users/patrickmcelhaney/code/nodejs-cucumber-sample

~/code/nodejs-cucumber-sample (master)
$ npm install --dev
npm WARN install Usage of the `--dev` option is deprecated. Use `--only=dev` instead.
nodejs-cucumber-sample@0.0.1 /Users/patrickmcelhaney/code/nodejs-cucumber-sample
└─┬ chai@1.10.0 
  ├── assertion-error@1.0.0 
  └─┬ deep-eql@0.1.3 
    └── type-detect@0.1.1 


~/code/nodejs-cucumber-sample (master)
$ npm test

> nodejs-cucumber-sample@0.0.1 test /Users/patrickmcelhaney/code/nodejs-cucumber-sample
> cucumber.js

Feature: Calculate

  Scenario: Add two numbers
    Given the input "2+2"
    When the calculator is run
    Then the output should be "4"

  Scenario: Subtract two numbers
    Given the input "9-4"
    When the calculator is run
    Then the output should be "5"

Failures:

1) Scenario: Add two numbers - features/calculator.feature:3
   Step: Before 
   Step Definition: features/support/hooks.js:15
   Message:
     TypeError: callback is not a function
         at World.<anonymous> (/Users/patrickmcelhaney/code/nodejs-cucumber-sample/features/support/hooks.js:18:9)
         at _combinedTickCallback (node.js:376:9)
         at process._tickCallback (node.js:407:11)
         at Function.Module.runMain (module.js:449:11)

2) Scenario: Add two numbers - features/calculator.feature:3
   Step: After 
   Step Definition: features/support/hooks.js:28
   Message:
     TypeError: callback is not a function
         at World.<anonymous> (/Users/patrickmcelhaney/code/nodejs-cucumber-sample/features/support/hooks.js:31:9)
         at _combinedTickCallback (node.js:376:9)
         at process._tickCallback (node.js:407:11)
         at Function.Module.runMain (module.js:449:11)

3) Scenario: Subtract two numbers - features/calculator.feature:8
   Step: Before 
   Step Definition: features/support/hooks.js:15
   Message:
     TypeError: callback is not a function
         at World.<anonymous> (/Users/patrickmcelhaney/code/nodejs-cucumber-sample/features/support/hooks.js:18:9)
         at _combinedTickCallback (node.js:376:9)
         at process._tickCallback (node.js:407:11)
         at Function.Module.runMain (module.js:449:11)

4) Scenario: Subtract two numbers - features/calculator.feature:8
   Step: After 
   Step Definition: features/support/hooks.js:28
   Message:
     TypeError: callback is not a function
         at World.<anonymous> (/Users/patrickmcelhaney/code/nodejs-cucumber-sample/features/support/hooks.js:31:9)
         at _combinedTickCallback (node.js:376:9)
         at process._tickCallback (node.js:407:11)
         at Function.Module.runMain (module.js:449:11)

2 scenarios (2 failed)
6 steps (6 skipped)
0m00.004s
npm ERR! Test failed.  See above for more details.

~/code/nodejs-cucumber-sample (master)
$ node -v
v5.9.0
```

I managed to get a demo working a few months ago using Selenium instead of Zombie, but that's not working either at this point.

https://github.com/pmcelhaney/cucumber-test/tree/selenium

**Comment by kulykr** [comment]
I have exactly the same issues

**Comment by kulykr** [comment]
Seems to be the hooks.js file (features\support\hooks.js)

I read somewhere in cucumber README.md that callbacks are no longer used

I used this hooks.js instead (since there is no setup or teardown):

```
/**
 * @function
 *
 * Hooks can be used to prepare and clean
 * the environment before and after
 * each scenario is executed
 */
module.exports = function() {
    /**
     * To run something before every scenario,
     * use before hooks
     *
     * @param  {Function} callback a done callback from cucumber.js
     */
    this.Before( function () {

        //don't forget to tell cucumber when your done
    });


    /**
     * To run something after every scenario,
     * use after hooks
     *
     * @param  {Function} callback a done callback from cucumber.js
     */
    this.After(function() {

        //don't forget to tell cucumber when your done
    });
}

```
